### ISSUE TITLE
Configurable product with > 300 Children

### ISSUE THREAD

**Issue by bragento** [danslo/ApiImport#19]
We are currently experiencing limitations when trying to import/save configurable products with more than ~300 child products. In that case the configurable product can't be saved correctly leading to erroneous behaviour.
Bypassing the case by assinging the children through admin or by loading and saving the product directly seems to work on the other hand.

Are there any known limitations and more elegant ways to bypass those?

Thanks again for your time

Regards

Amir

**Comment by danslo** [comment]
Closing this for now. Please re-open if you can demonstrate an example that is slow.
