### ISSUE TITLE
Categories import. Only super categories are allowed?

### ISSUE THREAD

**Issue by phpcoder2011** [danslo/ApiImport#27]
I tried to import root categories (under `Default Category`). It works fine. But it seems there is no support to import subcategories (for example if i want to import `Toners` sub category to `Default Category/Accessories` (`Accessories` is sub-category of `Default Category`)? It makes no sense then to use this tool. Anyway at least product import works great. Thanks for that!

**Comment by danslo** [comment]
Sorry for the late reply.

That is of course perfectly possible, just use a slash-separated path to your category. See this example:

```php
<?php

require_once 'app/Mage.php';

Mage::app('admin');

$import = Mage::getModel('api_import/import_api');
$import->importEntities(
    array(
        array(
            '_root'     => 'Default Category',
            '_category' => 'Accesoires/Toners',
            'name'      => 'Toners',
            'available_sort_by' => 'position',
            'default_sort_by'   => 'position',
            'include_in_menu'   => 'yes',
            'is_active'         => 'yes'
        )
    ),
    Danslo_ApiImport_Model_Import_Entity_Category::getEntityTypeCode()
);
```

**Comment by phpcoder2011** [comment]
Thank you!
