### ISSUE TITLE
Products import. Adding product to category and root of that category. How to?

### ISSUE THREAD

**Issue by phpcoder2011** [danslo/ApiImport#29]
I tried to add products to "Toners" category by specifying "_category => 'Accessories/Toners'" for each product. And it works great. Products are added to "Toners". But "Toners" category is part of "Accessories" category. Is it possible/how to add product not only to "Toners" but also to it's parent called "Accessories"? So when i click "Accessories" i want to see all products of it's sub-categories.

**Comment by willy-ahva** [comment]
Hi @phpcoder2011,
You can add as many "_category" as you want follow this : 
``` php

**Comment by danslo** [comment]
Pretty much what @willy-ahva said :+1:

**Comment by phpcoder2011** [comment]
Hi @willy-ahva! Thank you for the answer! I did create CSV to see what you mean and i assigned manually 2 categories "Accessories" and "Accessories/Toners" for a product. I see there are 2 lines in CSV for categories: "Accessories" and "Accessories/Toners". I see your example looks similar, but i still don't get it. I thought i did and tried 2 variants, but it didn't work. Here they are:

variant 1:
<pre>
[sku1] => Array
	(
		[_product_websites] => base
		[status] => 1
		[visibility] => 4
		[tax_class_id] => 0
		[is_in_stock] => 1
		[_media_is_disabled] => 0
		[_media_attribute_id] => 88
		[_attribute_set] => my_family
		[sku] => sku1
		[_type] => simple
		[name] => Product name
		[price] => 3.1211
		[weight] => 0
		[qty] => 7		
		[description] => Product description
		[short_description] => Short description
		[manufacturer] => 
		[image] => \my_family\sku1\0.jpg
		[thumbnail] => \my_family\sku1\0.jpg
		[small_image] => \my_family\sku1\0.jpg
		[_media_image] => \my_family\sku1\0.jpg
		[0] => Array
			(
				[_category] => Accessories/Toners
				[_root_category] => Default Category
			)

		[1] => Array
			(
				[_category] => Accessories
				[_root_category] => Default Category
			)

	)
</pre>	

variant 2:

<pre>Array
(
    [0] => Array
        (
            [_product_websites] => base
            [status] => 1
            [visibility] => 4
            [tax_class_id] => 0
            [is_in_stock] => 1
            [_media_is_disabled] => 0
            [_media_attribute_id] => 88
            [_attribute_set] => my_family
            [sku] => sku1
            [_type] => simple
            [name] => Product name
            [price] => 3.1211
            [weight] => 0
            [qty] => 7
            [_category] => Accessories/Toners
            [description] => Product description
            [short_description] => Short description
            [manufacturer] => 
            [image] => \my_family\sku1\0.jpg
            [thumbnail] => \my_family\sku1\0.jpg
            [small_image] => \my_family\sku1\0.jpg
            [_media_image] => \my_family\sku1\0.jpg
        )

    [1] => Array
        (
            [_category] => Accessories
            [_root_category] => Default Category
        )

)</pre>

What am I doing wrong?

**Comment by danslo** [comment]
The first one is definitely wrong. The second comes closer but you are missing ``_root_category`` in the first array.

**Comment by phpcoder2011** [comment]
Thanks. I tried it, but still no products in Accessories.
The only current way i do this is immediate re-import with APPEND behavior and assigning categories i want. So 2 imports are needed currently - 1 to insert products and 2nd to append parent category. I thought it's an overkill that's why I asked if there is more suitable way.

**Comment by danslo** [comment]
I use the following script to reproduce:

```php
<?php

require_once 'app/Mage.php';

Mage::app('admin');

$products = Mage::helper('api_import/test')->generateRandomSimpleProduct(1);

$products[1]['_root_category'] = 'Default Category';
$products[1]['_category']      = 'Accesoires';
$products[2]['_category']      = 'Accesoires/Toners';

try {
    Mage::getModel('api_import/import_api')->importEntities($products, 'catalog_product');
} catch (Exception $e) {
    printf("%s: %s\n", $e->getMessage(), $e->getCustomMessage());
}
```

As you can see, default behavior (replace), the product did not exist before, and it's properly associated with the categories.

**Comment by phpcoder2011** [comment]
Ok, thank you, i'll look what i missed in my code!

**Comment by danslo** [comment]
By the way, make absolutely sure the category names match, I just noticed I named mine ``Accesoires`` and you ``Accessories``, and the correct spelling is ``Accessoires``, lol.

**Comment by phpcoder2011** [comment]
You were right, i made a typo, but i messed with variable names. Re-checked 100 times and could find it.. Now it works perfectly! THANK YOU for help!

**Comment by danslo** [comment]
:+1:
