### ISSUE TITLE
Issue on product import from csv

### ISSUE THREAD

**Issue by Ditchou** [danslo/ApiImport#30]
Hello,

When I try to import from a csv using the magento import workflow I have this issue : 

Fatal error: Call to undefined method Mage_ImportExport_Model_Import_Entity_Product::getStores() in app/code/local/Danslo/ApiImport/Model/Import/Entity/Product/Type/Bundle.php on line 113

Any idea?

**Comment by Ditchou** [comment]
I also have an issue using this code : 

$api = Mage::getModel('api_import/import_api');
$products = Mage::helper("api_import/test")->generateRandomConfigurableProduct(2);
$api->importEntities($products);

Notice: Undefined index: sku  in app/code/core/Mage/ImportExport/Model/Import/Entity/Product.php on line 1752

**Comment by danslo** [comment]
@Ditchou What version of Magento? The second one is a notice that has been fixed in later versions. The former error worries me more.

**Comment by Ditchou** [comment]
@danslo I tried on 1.9 and 1.7

**Comment by danslo** [comment]
The first issue should be fixed by that commit. Sorry, I never actually use the backend import.

The second one is a core 'bug' (though you can safely ignore it) and I'm pretty sure it should be fixed in 1.9.

**Comment by Ditchou** [comment]
Np, Happy to find an issue :) I will use your module a lot, so, I will maybe find others
