### ISSUE TITLE
import CSV file

### ISSUE THREAD

**Issue by farmaworld** [danslo/ApiImport#32]
i want to import a CSV file in my Magento, it's possible?
thanks

**Comment by danslo** [comment]
ApiImport does not support CSV files directly, but it should take 3 or 4 lines of code using [fgetcsv](http://php.net/manual/en/function.fgetcsv.php) to get an array from a CSV file.

**Comment by barryvdh** [comment]
Example here: https://github.com/danslo/ApiImport/pull/44
