### ISSUE TITLE
Import Customers - How to

### ISSUE THREAD

**Issue by desarrollo-rollpix** [danslo/ApiImport#34]
Hi,

I need to import Customers data like Address or billing info, How I can import this type of info? Where I can see an example about all the info that I can import? (Customer, Product,...)

Thanks in advance

**Comment by jamie-selesti** [comment]
I would like to know how to do this too

**Comment by danslo** [comment]
The test helper generates some sample customers:
https://github.com/danslo/ApiImport/blob/master/code/Helper/Test.php#L443

Or even easier, just use the export function in Import/Export on some sample customers :)
