### ISSUE TITLE
How to import product with multi images

### ISSUE THREAD

**Issue by dominicnguyen810** [danslo/ApiImport#40]
Hello @danslo,

I try to import product with multi images(include image, small_image, thumbnail) by my configuration but not success:

        array(
                    'sku'                => 'some_sku_' . $i,
                    '_type'              => 'simple',
                    'name'               => 'Some product ( ' . $i . ' )',
                    'price'              => rand(1, 1000),
                    'weight'             => rand(1, 1000),
                    'qty'                => rand(1, 30),
                    'image'              => '/example_image.png',
                    'small_image'        => '/example_image1.png',
                    'thumbnail'          => '/example_image2.png',
                    'image_content'      => base64_encode(file_get_contents('example_image.png')),
                    '_media_image'       => '/example_image.png',
                    '_media_is_disabled' => '0'
                )

Can you give some guide for this.

Thanks!

**Comment by dominicnguyen810** [comment]
Hi @danslo,

I've found a way to configure to import multi images, but only Base Image is selected.

array(
                'sku'                => 'some_sku_' . $i,
                '_type'              => 'simple',
                'name'               => 'Some product ( ' . $i . ' )',
                'price'              => rand(1, 1000),
                'weight'             => rand(1, 1000),
                'qty'                => rand(1, 30),
                'image'              => '/example_image.png',
                'image_content'      => base64_encode(file_get_contents('example_image.png')),
                '_media_image'       => '/example_image.png',
                '_media_is_disabled' => '0'
            ),
array(
                'small_image'        => '/example_image1.png',
                'image_content'      => base64_encode(file_get_contents('example_image1.png')),
                '_media_image'       => '/example_image1.png',
                '_media_is_disabled' => '0'
            ),
array(
                'thumbnail'        => '/example_image1.png',
                'image_content'      => base64_encode(file_get_contents('example_image2.png')),
                'thumbnail_content'       => '/example_image2.png',
                '_media_is_disabled' => '0'
            )

Please see detail in this link: http://prntscr.com/96n8k0

**Comment by davidverholen** [comment]
hey, thumbnail and small_image also must be in the first array

**Comment by dominicnguyen810** [comment]
Hi @davidverholen,

Thanks for quick reply.
I have tried add thumbnail and small_image to first array, but not work.
array(
'sku' => 'some_sku_' . $i,
'_type' => 'simple',
'name' => 'Some product ( ' . $i . ' )',
'price' => rand(1, 1000),
'weight' => rand(1, 1000),
'qty' => rand(1, 30),
'image' => '/example_image.png',
'small_image' => '/example_image1.png',
'thumbnail' => '/example_image1.png',
'image_content' => base64_encode(file_get_contents('example_image.png')),
'_media_image' => '/example_image.png',
'_media_is_disabled' => '0'
),

Can you give some hints for me?

**Comment by dominicnguyen810** [comment]
Hi @davidverholen,

Thanks for quick reply, it works well.
