### ISSUE TITLE
How to import related, cross-sell, up-sell products?

### ISSUE THREAD

**Issue by dominicnguyen810** [danslo/ApiImport#41]
Hi guys,

I want  to import related, cross-sell, up-sell products.
Can you give some hints for me?

Thanks & Best Regards.

**Comment by dominicnguyen810** [comment]
Hi guys,

Can you check it for me, please?

**Comment by danslo** [comment]
Use these columns:
https://github.com/OpenMage/magento-mirror/blob/4bc632edf76c1008b7dccde3e5c7357ce2c00087/app/code/core/Mage/ImportExport/Model/Import/Entity/Product.php#L358
