### ISSUE TITLE
How to add store specific description to category?

### ISSUE THREAD

**Issue by iventura** [danslo/ApiImport#43]
I have to save different descriptions for each store, but "_store" will be ignored:

My Array:
                    array(
                        'name' => $name,
                        '_store' => '1',                        
                        'description' => 'description',
                        '_category' => $path,
                        'url_key' => $item->getData('url_key')
                    ) 
May be i have to create more as one array item and divide '_category' and '_store' fields?

Thank you in advance!

**Comment by danslo** [comment]
You should use storecode, not store ID in that column.

Something like:

```
array(
    'name' => $name,
    '_store' => 'default',
    'description' => 'My English Description',
    [ ... ]
),
array(
    '_store' => 'french',
    'description' => 'Ma Boutique Française'
)
```
