### ISSUE TITLE
Category Import/Image Import 

### ISSUE THREAD

**Issue by idmistir** [danslo/ApiImport#45]
In trying to import a large tree of categories I seem to be unable to find a way to structure the tree properly. I stepped through the code and I saw that you use _root to specify where each category should fall under, and _category as well, maybe as a parent. However, wouldn't it be better if we were able to specify parent id? I do have this information I am just unsure how to structure the actual entity to do the import.

Also the same question applies for multiple product image import.

Thank you so much! I think this is the fastest importer I've used to date by a long shot! For 7k prods magmi did 244.9sec and api import did 94!

**Comment by danslo** [comment]
Just going to be pasting this from IRC, if it didn't get to you.

```
(20:45:24) danslo: idmistir: the category importer follows the same convention as product<>category association, it accepts a slash separated path to the parent
(20:47:02) danslo: _root is just what refers to the Root Category, which are just top level categories (they're used to give store groups other category trees)
(20:47:55) phtes: hello unicorn
(20:48:28) danslo: so for example if you were to create a tree like:  Clothes > Shirts > Green Shirts, you would have 3 rows, all with the same Root Category, and with 'name' being
(20:48:28) danslo: Clothes
(20:48:28) danslo: Clothes / Shirts
(20:48:28) danslo: Clothes / Shirts / Green Shirts
(20:48:42) danslo: the importer will figure out parent categories based on those slashes
(20:48:53) danslo: (there probably shouldnt be spaces between there, cant remember)
(20:49:18) danslo: https://github.com/danslo/ApiImport/blob/master/code/Model/Import/Entity/Category.php#L733
(20:49:21) danslo: see this, for how it does that
```
