### ISSUE TITLE
Upsell products are being removed

### ISSUE THREAD

**Issue by jensvandorpe** [danslo/ApiImport#47]
Hi,

When I run the product import without the upsell products in the array (BEHAVIOR_REPLACE), the upsell products are removed. 

How could this be prevented?

Thanks in advance

**Comment by danslo** [comment]
That's the intended behavior for REPLACE. You can either use append behavior or make a rewrite that adjusts [this](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/ImportExport/Model/Import/Entity/Product.php#L1142) code.
