### ISSUE TITLE
How to get custom product field data from third party Api webservice like Cin7.com ?

### ISSUE THREAD

**Issue by hashir-dhattiwala** [danslo/ApiImport#48]
Hello Danslo,

I have an urgent problem which I would like to be resolved.

I am using your module to fetch product data from a third party api cin7.com.
They have setting for updating products directly from cin7.com to Magento.

Now when I use that setting "Update Products" link, I get all the usual Magento product values like below, but the product in their site also have some custom attributes like "Wholesale price" etc.

```
[0] => Array
        (
            [sku] => 191010
            [_type] => simple
            [_store] => 
            [_attribute_set] => Default
            [_product_websites] => base
            [name] => product name
            [description] => <ul><li>description....</li></ul> 
            [short_description] => <ul><li>short description....</li></ul> 
            [weight] => 25
            [status] => 1
            [visibility] => 4
            [price] => 508.20
            [special_price] => 
            [special_from_date] => 
            [special_to_date] => 
            [tax_class_id] => 2
            [qty] => 0
            [is_in_stock] => 0
            [manage_stock] => 1
            [cin7_import] => 2016-09-21 12:40:39
        )
```
Now how do I add some custom fields from that site so that they are also transferred to my Magento site in devlopment server ?

I think I need to override Magento default wsdl model for this ?

Please reply Asap.

Waiting...
Hashir

**Comment by danslo** [comment]
The attributes only have to exist in Magento backend, the WSDL just accepts a generic array so it doesn't need to be extended.

**Comment by hashir-dhattiwala** [comment]
Thanks for you reply Daniel,

Will ask you more queries on this if need arises.

Regards,
Hashir
