### ISSUE TITLE
How to integrate the Order import/update api (from third-party endpoint/site to Magento) with in your module ?

### ISSUE THREAD

**Issue by hashir-dhattiwala** [danslo/ApiImport#50]
Hello Daniel,

Thanks for your ApiImport module, it helped us lot for importing Products and setting  their attributes into Magento Admin from a third-party site Cin7.

Do you have any other module through which we can import/update Orders using Api concept just like we did with Products ?

Or any hint/guideline/suggestion you can provide for importing Orders from third party site(i.e. Cin7.com) to Magento ?

Waiting for your reply....

Regards,
Hashir

**Comment by danslo** [comment]
ImportExport doesn't support orders and so naturally ApiImport doesn't either as a result. [Here](http://magento.stackexchange.com/a/6627/140) is an example on how to do it with regular SOAP API.
