### ISSUE TITLE
Incorrect modman file path

### ISSUE THREAD

**Issue by thomashery** [danslo/ApiImport#52]
Hi,
your mode file is incorrectly setup and this results in the creation of a code folder within the module:
docroot/app/code/local/Danslo/ApiImport/code
Can you please fix it?

**Comment by danslo** [comment]
[This](https://github.com/danslo/ApiImport/commit/2c823b76588f03ea06facca9afad936006d2fd80) commit might have fixed it. Try dev-master version, if it works I can tag a new release.
